apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-proxy
  name: kube-proxy-haproxy
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9080
    protocol: TCP
  selector:
    k8s-app: kube-proxy
